#pragma once
/* XPM */
static const char* const new_xpm[] = {
	/* columns rows colors chars-per-pixel */
	"16 15 29 1",
	"* c #97C4E7",
	"- c #72A8D2",
	": c #FFFFFF",
	"9 c #839CB5",
	"o c #6B98B8",
	"X c #5A89A6",
	"# c #3A749C",
	", c #D1E5F5",
	"0 c #85A7BC",
	"$ c #C3DDF1",
	"8 c #749BB4",
	"; c #5F9BC8",
	"  c None",
	"+ c #538DB3",
	"= c #85BBE2",
	"3 c #EFF6FC",
	"O c #6591AE",
	"5 c #F7FBFD",
	"7 c #FAFCFE",
	"< c #DAEAF7",
	"4 c #E9F3FA",
	"6 c #FDFDFE",
	"1 c #E2EFF8",
	". c #8EA9BC",
	"% c #B6D5EE",
	"& c #A5CCEA",
	"> c #ACE95B",
	"2 c #F4F9FD",
	"@ c #4581AA",
	/* pixels */
	"   .XoOO+@#.    ",
	"   .$$%&*=O-;   ",
	"  @@@@$%&*O:*o  ",
	"  @>>@$$%&O::*o ",
	"@@@>>@@@$%OOoO+ ",
	"@>>>>>>@,$%&*=+ ",
	"@>>>>>>@<,$%&*+ ",
	"@@@>>@@@1<,$%&O ",
	"  @>>@2341<,$%O ",
	"  @@@@52341<,$o ",
	"   .:6752341<,8 ",
	"   .::6752341<8 ",
	"   .:::67523419 ",
	"   .::::6752340 ",
	"   ............ "
};

/* XPM */
static const char* const open_xpm[] = {
	/* columns rows colors chars-per-pixel */
	"16 15 36 1",
	"6 c #9BACC2",
	"< c #9AEA53",
	"9 c #94A5BD",
	"5 c #839CB5",
	"; c #4D7492",
	". c #376485",
	"$ c #7F99B4",
	"r c #D1D9E5",
	"7 c #EAEDF3",
	"@ c #CAD2DC",
	"% c #718BA7",
	"t c #BECAD9",
	"& c #65839D",
	"0 c #DCE2EA",
	"4 c #F5F6F7",
	"w c #597B9A",
	"O c #8DA0B9",
	"  c None",
	"+ c #467291",
	"u c #305F81",
	"= c #B4C4D3",
	"# c #CAE2AA",
	"1 c #FAFCFE",
	"3 c #A8B6CA",
	"q c #E4E9ED",
	"8 c #EEF1F3",
	"X c #215579",
	"2 c #7F97B0",
	": c #B3BFD1",
	"y c #7A90AC",
	", c #C2CBDB",
	"- c #ADD668",
	"* c #B6D791",
	"e c #CAD6E1",
	"o c #DFF0D0",
	"> c #BBC4D6",
	/* pixels */
	"                ",
	"     ....       ",
	"XXXXX .oo.      ",
	"XOOOO+@.#o.     ",
	"XOOOO$%&.*oXXX  ",
	"XOOOOOOO.*oX=X  ",
	"XOXXXX...-oXXXX;",
	"XOX:>,.<<<<<oX1;",
	"X2X3:>,.<<<oX4=;",
	"XX563:>>.<oX78; ",
	"XXO963:>>.X0q7; ",
	"Xw2O963:>>er0t; ",
	"X&y2O963:>,er;  ",
	"uXXXXXXXXXXXX;  ",
	"                "
};

static const char* const folder_open_xpm[] = {
	/* columns rows colors chars-per-pixel */
	"16 15 31 1",
	"6 c #9BACC2",
	"w c #547B99",
	"5 c #94A5BD",
	". c #376485",
	"; c #F1F4F7",
	"o c #7F99B4",
	"2 c #D1D9E5",
	"- c #EAEDF3",
	"O c #718BA7",
	"0 c #65839D",
	"* c #DCE2EA",
	": c #F5F6F7",
	"7 c #597B9A",
	"X c #8DA0B9",
	"  c None",
	"+ c #467291",
	"q c #305F81",
	"& c #D6DFE7",
	"3 c #6A89A2",
	"1 c #A8B6CA",
	"= c #E4E9ED",
	"> c #F8F9FA",
	", c #FDFDFE",
	"9 c #215579",
	"8 c #7F97B0",
	"@ c #B3BFD1",
	"< c #7A90AC",
	"$ c #C2CBDB",
	"4 c #A2B3C5",
	"% c #CAD6E1",
	"# c #BBC4D6",
	/* pixels */
	"                ",
	".....           ",
	".XXXo.          ",
	".XXXXO........  ",
	".XXXXXXXXXXXX.  ",
	".XXXXXXXXXXXX.  ",
	".X++++++++++++++",
	".X+@#$%&*=-;:>,+",
	".<.1@#$%2*=-;:23",
	"..X41@#$%2*=-;3 ",
	"..X561@#$%2*=-3 ",
	".78X561@#$%2*%3 ",
	"90<8X561@#$%23  ",
	"q++++++++++++w  ",
	"                "
};

static const char* const new_dir_xpm[] = {
	/* columns rows colors chars-per-pixel */
	"16 15 22 1",
	"X c Black",
	"> c #9BACC2",
	"o c #547897",
	"1 c #7F99B4",
	"O c #D1D9E5",
	"< c #EAEDF3",
	"# c #CAD2DC",
	"3 c #718BA7",
	"@ c #BECAD9",
	"& c #E1E6EE",
	"; c #F5F6F7",
	". c #FFFF00",
	", c #8DA0B9",
	"  c None",
	"% c #D6DFE7",
	"$ c #D2D9E0",
	"- c #ADBACE",
	"= c #EEF1F3",
	"+ c #B3BFD1",
	"2 c #7A90AC",
	": c #A2B3C5",
	"* c #E5EAF1",
	/* pixels */
	"         .X .XX.",
	" ooooo    .X.X. ",
	" oOOOOo  XX...XX",
	" oooooooo.......",
	" o+@#$%&*XX...XX",
	" o+@#$%&*=.X.X. ",
	" o-+@#O%&.X;.X .",
	" o:-+@#O%&*=;o  ",
	" o>:-+@#O%&*=o  ",
	" o,>:-+@#O%&<o  ",
	" o1,>:-+@#O%&o  ",
	" o21,>:-+@#O%o  ",
	" o321,>:-+@#Oo  ",
	" ooooooooooooo  ",
	"                "
};

static const char* const removable_xpm[] = {
	/* columns rows colors chars-per-pixel */
	"16 15 23 1",
	"@ c #C3C3C4",
	"4 c #FFFFFF",
	"o c #D5D6D8",
	"> c #7A92A3",
	". c #8497A5",
	"% c #ACAEB2",
	"2 c #4A7898",
	": c #DCE2EA",
	", c #F5F6F7",
	"= c #EBEBEC",
	"$ c #B7B7B8",
	"  c None",
	"X c #DFE0E2",
	"* c #A6A8AD",
	"1 c #4C809F",
	"3 c #407598",
	"O c #CFCFD0",
	"; c #9EA2A8",
	"# c #BCBDBE",
	"+ c #C6C8CA",
	"- c #979BA0",
	"& c #E7E7E7",
	"< c #8FB0C3",
	/* pixels */
	"   .........    ",
	"   .XoO+@#$%.   ",
	"   .XoO+@#$%.   ",
	"  .&XoO+@#$%*.  ",
	"  .&XoO+@#$%*.  ",
	" .=&XoO+@#$%*-. ",
	" .=&XoO+@#$%*;. ",
	".:=&XoO+@#$%*;>.",
	".,=&XoO+@#$%*;-.",
	"<..............<",
	"<,=&XoO+@#$%%%%.",
	"<O1111122233*4*.",
	"<OOOOOOOOOOO***.",
	" <<<<<<<<<<<<<< ",
	"                "
};

static const char* const cut_xpm[] = {
	/* columns rows colors chars-per-pixel */
	"16 15 25 1",
	"6 c #D8BDC0",
	": c #C3C3C4",
	"- c #FFFFFF",
	". c #6C6D70",
	"2 c #AD3A45",
	"o c #DBDBDB",
	"# c #939495",
	"< c #E42234",
	"& c #C3C5C8",
	"; c #C6CCD3",
	"% c #B7B7B8",
	"  c None",
	"* c #DFE0E2",
	"5 c #B69596",
	"3 c #9C2A35",
	"1 c #CFCFD0",
	", c #AB5C64",
	"+ c #D2D3D4",
	"$ c #BCBDBE",
	"@ c #C6C8CA",
	"> c #CDC0C1",
	"O c #826F72",
	"X c #979BA0",
	"4 c #9B8687",
	"= c #9FA0A0",
	/* pixels */
	"   .X     .o    ",
	"   O.+   @.     ",
	"    O.   ..     ",
	"    O#$ %.&     ",
	"     O.*..      ",
	"     #%#..      ",
	"     O=-..      ",
	"     #%#;.      ",
	"     OO:=O      ",
	"  >,,<, ,<,,1   ",
	" ><23<1 1<32<1  ",
	" ,2 4<   <5 2,  ",
	" <, ,2   2, ,<  ",
	" 23,<5   5<,32  ",
	" 6225     522>  "
};
/* XPM */
static const char* const copy_xpm[] = {
	/* columns rows colors chars-per-pixel */
	"16 15 23 1",
	"o c #97C4E7",
	"* c #FFFFFF",
	"@ c #60A9DA",
	"= c #D1E5F5",
	"& c #C3DDF1",
	". c #7EA6C0",
	"  c None",
	"X c #2F93CD",
	"O c #85BBE2",
	", c #EFF6FC",
	"; c #DEEDF8",
	"+ c #72B2DD",
	"3 c #F7FBFD",
	"4 c #FAFCFE",
	": c #DAEAF7",
	"< c #E9F3FA",
	"1 c #E2EFF8",
	"- c #FDFDFE",
	"% c #B6D5EE",
	"$ c #A5CCEA",
	"> c #E5F0F9",
	"# c #AFD1EC",
	"2 c #F4F9FD",
	/* pixels */
	" .....XX        ",
	" .oO+@X#X       ",
	" .$oO+X##X      ",
	" .%$o........   ",
	" .&%$.*=&#o.-.  ",
	" .=&%.*;=&#.--. ",
	" .:=&.*>;=&.... ",
	" .>:=.*,>;=&#o. ",
	" .<1:.*2,>:=&#. ",
	" .2<1.*32,>:=&. ",
	" .32<.*432,>:=. ",
	" .32<.*-432,>:. ",
	" .....**-432,>. ",
	"     .***-432,. ",
	"     .......... "
};
/* XPM */
static const char* const paste_xpm[] = {
	/* columns rows colors chars-per-pixel */
	"16 15 25 1",
	"< c #FEECE4",
	"> c #FEE3D7",
	"O c #FFFFFF",
	"o c #7B767D",
	"% c #F79586",
	"& c #CAE1F3",
	"@ c #F08B62",
	"# c #FCCBB8",
	"- c #FDD8C9",
	"4 c #FFF8F4",
	"5 c #FFF5F0",
	"  c None",
	"$ c #F8AA8F",
	", c #EFF6FC",
	"1 c #F7FBFD",
	"2 c #FAFCFE",
	"; c #DAEAF7",
	": c #E9F3FA",
	"6 c #FFFAF8",
	". c #3C78A6",
	"3 c #FFF1ED",
	"X c #9B8687",
	"+ c #FBBCA4",
	"* c #B6D5EE",
	"= c #F4F9FD",
	/* pixels */
	"   ......       ",
	" .XoOOOOoo.     ",
	".+XOOOOOOX@.    ",
	".+XXXXXXXX@.    ",
	".#++$$%@.....   ",
	".##++$$%.&*.=.  ",
	".-##++$$.;&.==. ",
	".--##++$.:;.... ",
	".>--##++.,:;&*. ",
	".<>--##+.1,:;&. ",
	".<<>--##.21,:;. ",
	".3<<>--#.O21=:. ",
	".45<<>--....... ",
	".6453<>----.    ",
	"............    "
};
static const char* const deffile_xpm[] = {
	/* columns rows colors chars-per-pixel */
	"16 16 32 1",
	"= c #97C4E7",
	": c #72A8D2",
	"1 c #FFFFFF",
	"w c #839CB5",
	"X c #6B98B8",
	". c #5A89A6",
	"@ c #3A749C",
	", c #D1E5F5",
	"< c #67A1CF",
	"> c #F1F4F7",
	"e c #85A7BC",
	"% c #C3DDF1",
	"0 c #749BB4",
	"2 c #7EA6C0",
	"; c #5F9BC8",
	"  c None",
	"O c #538DB3",
	"- c #85BBE2",
	"$ c #D6DFE7",
	"9 c #EFF6FC",
	"o c #6591AE",
	"4 c #F7FBFD",
	"8 c #FAFCFE",
	"6 c #DAEAF7",
	"7 c #E9F3FA",
	"q c #FDFDFE",
	"3 c #E2EFF8",
	"# c #8EA9BC",
	"& c #B6D5EE",
	"* c #A5CCEA",
	"5 c #F4F9FD",
	"+ c #4581AA",
	/* pixels */
	"  ..XooO+@#$    ",
	"  .%%&*=-;:;>   ",
	"  .,,%&*=<1=X>  ",
	"  #%%%%&*211=X  ",
	"  #3-----<oXoO  ",
	"  #3456,%&*=-O  ",
	"  #3--------=O  ",
	"  #355736,%&*o  ",
	"  #3--------&o  ",
	"  #38459736,%X  ",
	"  #3--------,0  ",
	"  #31q84597360  ",
	"  #3--------3w  ",
	"  #3111q84597e  ",
	"  ##########e#  ",
	"                "
};
static const char* const filesave_xpm[] = {
	/* columns rows colors chars-per-pixel */
	"16 15 21 1",
	"O c #FFFFFF",
	"> c #D5D6D8",
	"; c #446A8C",
	"1 c #CAD2DC",
	": c #C0C7D1",
	"  c #5F666D",
	"% c #A5B0BA",
	"o c #65839D",
	", c #DCE2EA",
	"< c #C3C5C8",
	"- c #E1E6EE",
	"* c #C6CCD3",
	". c None",
	"$ c #305F81",
	"2 c #D6DFE7",
	"= c #D2D9E0",
	"& c #B7BFC7",
	"X c #1B4467",
	"# c #BCBDBE",
	"@ c #7A90AC",
	"+ c #5D7C93",
	/* pixels */
	"               .",
	" XoOOOOOOOOO+X .",
	" @oO#######O+@ .",
	" @oOOOOOOOOO+@ .",
	" @oO#######O+@ .",
	" @oOOOOOOOOO+@ .",
	" @@+++++++++@@ .",
	" @@@@@@@@@@@@@ .",
	" @@@$$$$$$$$@@ .",
	" @@$%%%&*=-O$@ .",
	" @@$%X;;*=-O$@ .",
	" @@$%X;;:>,O$@ .",
	" @@$%X;;<12O$@ .",
	" @@$<<2OOOOO$@ .",
	".             .."
};
static const char* const close_xpm[] = {
"12 10 2 1",
"         c None",
"X        c black",
"            ",
"  XX    XX  ",
"   XX  XX   ",
"    XXXX    ",
"     XX     ",
"    XXXX    ",
"   XX  XX   ",
"  XX    XX  ",
"            ",
"            " };
static const char* const helpicon_xpm[] = {
	/* columns rows colors chars-per-pixel */
	"32 32 6 1",
	"  c Gray0",
	". c Blue",
	"X c #808080808080",
	"o c #c0c0c0c0c0c0",
	"O c Gray100",
	"+ c None",
	/* pixels */
	"+++++++++++XXXXXXXX+++++++++++++",
	"++++++++XXXoOOOOOOoXXX++++++++++",
	"++++++XXoOOOOOOOOOOOOoXX++++++++",
	"+++++XoOOOOOOOOOOOOOOOOoX+++++++",
	"++++XOOOOOOOOOOOOOOOOOOOO ++++++",
	"+++XOOOOOOOo......oOOOOOOO +++++",
	"++XOOOOOOOo.oOO....oOOOOOOO ++++",
	"+XoOOOOOOO..OOOO....OOOOOOOo +++",
	"+XOOOOOOOO....OO....OOOOOOOO X++",
	"XoOOOOOOOO....Oo....OOOOOOOOo X+",
	"XOOOOOOOOOo..oO....OOOOOOOOOO X+",
	"XOOOOOOOOOOOOOo...OOOOOOOOOOO XX",
	"XOOOOOOOOOOOOO...OOOOOOOOOOOO XX",
	"XOOOOOOOOOOOOO..oOOOOOOOOOOOO XX",
	"XOOOOOOOOOOOOO..OOOOOOOOOOOOO XX",
	"XoOOOOOOOOOOOOOOOOOOOOOOOOOOo XX",
	"+XOOOOOOOOOOOo..oOOOOOOOOOOO XXX",
	"+XoOOOOOOOOOO....OOOOOOOOOOo XXX",
	"++XOOOOOOOOOO....OOOOOOOOOO XXX+",
	"+++ OOOOOOOOOo..oOOOOOOOOO XXXX+",
	"++++ OOOOOOOOOOOOOOOOOOOO XXXX++",
	"+++++ oOOOOOOOOOOOOOOOOo XXXX+++",
	"++++++  oOOOOOOOOOOOOo  XXXX++++",
	"+++++++X   oOOOOOOo   XXXXX+++++",
	"++++++++XXX   oOOO XXXXXXX++++++",
	"++++++++++XXXX OOO XXXXX++++++++",
	"+++++++++++++X OOO XX+++++++++++",
	"+++++++++++++++ OO XX+++++++++++",
	"++++++++++++++++ O XX+++++++++++",
	"+++++++++++++++++  XX+++++++++++",
	"++++++++++++++++++XXX+++++++++++",
	"+++++++++++++++++++XX+++++++++++"
};


static const char* const tipicon_xpm[] = {
	/* columns rows colors chars-per-pixel */
	"32 32 9 1",
	"$ c Black",
	"O c #FFFFFF",
	"@ c #808080",
	"+ c #000080",
	"o c #E8EB01",
	"  c None",
	"X c #FFFF40",
	"# c #C0C0C0",
	". c #ABAD01",
	/* pixels */
	"                                ",
	"             .....              ",
	"           ..XXXXX..            ",
	"         ..XXXXXXXXo..          ",
	"        .XXXOXXXXXXXoo.         ",
	"        .XOOXXX+XXXXXo.         ",
	"       .XOOOXX+++XXXXoo.        ",
	"       .XOOXXX+++XXXXXo.        ",
	"      .XOOOXXX+++XXXXXXo.       ",
	"      .XOOXXXX+++XXXXXXo.       ",
	"      .XXXXXXX+++XXXXXXX.       ",
	"      .XXXXXXX+++XXXXXXo.       ",
	"      .XXXXXXX+++XXXXXoo.       ",
	"       .XXXXXX+++XXXXXo.        ",
	"       .XXXXXXX+XXXXXXo.        ",
	"        .XXXXXXXXXXXXo.         ",
	"        .XXXXX+++XXXoo.         ",
	"         .XXXX+++XXoo.          ",
	"          .XXXXXXXXo.           ",
	"          ..XXXXXXo..           ",
	"           .XXXXXo..            ",
	"           @#######@            ",
	"           @@@@@@@@@            ",
	"           @#######@            ",
	"           @@@@@@@@@            ",
	"           @#######@            ",
	"            @@@@@@@             ",
	"              ###               ",
	"              $$$               ",
	"                                ",
	"                                ",
	"                                "
};
/* XPM */
static const char* const missimg_xpm[] = {
	/* columns rows colors chars-per-pixel */
	"32 32 5 1",
	"X c Black",
	"o c #FFFFFF",
	"  c None",
	". c #C0C0C0",
	"O c #E0E0E0",
	/* pixels */
	" .............................X ",
	" .ooooooooooooooooooooooooooooX ",
	" .ooooooooooooooooooooooooooooX ",
	" .ooOOOOOOOOOOOOOOOOOOOOOOOOooX ",
	" .ooOOOOOOOOOOOOOOOOOOOOOOOOooX ",
	" .ooOOOOOOOOOOOOOOOOOOOOOOOOooX ",
	" .ooOOOOOOOOOOOOOOOOOOOOOOOOooX ",
	" .ooOOOOOOOOOOOOOOOOOOOOOOOOooX ",
	" .ooOOOOOOOOOOOOOOOOOOOOOOOOooX ",
	" .ooOOOOOOOXOOOOOOOOOOOOOOOOooX ",
	" XXXOOOOOXX XOOOOOOOOOOOOOOOooX ",
	"    XXXXX    XOOOOOOOOOOOOOOooX ",
	"              XOOOXXXOOOOOOOooX ",
	"               XXX   XXOOOOOooX ",
	"                       XOOOOooX ",
	" .                      XOOOooX ",
	" ..                      XXOooX ",
	" .o..                      XooX ",
	" .ooO...                    XXX ",
	" .ooOOOO..........              ",
	" .ooOOOOOOOOOOOOOO..            ",
	" .ooOOOOOOOOOOOOOOOO..          ",
	" .ooOOOOOOOOOOOOOOOOOO......... ",
	" .ooOOOOOOOOOOOOOOOOOOOOOOOOooX ",
	" .ooOOOOOOOOOOOOOOOOOOOOOOOOooX ",
	" .ooOOOOOOOOOOOOOOOOOOOOOOOOooX ",
	" .ooOOOOOOOOOOOOOOOOOOOOOOOOooX ",
	" .ooOOOOOOOOOOOOOOOOOOOOOOOOooX ",
	" .ooOOOOOOOOOOOOOOOOOOOOOOOOooX ",
	" .ooooooooooooooooooooooooooooX ",
	" .ooooooooooooooooooooooooooooX ",
	" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX "
};
/* XPM */
static const char* const showBig_xpm[] = {
	/* columns rows colors chars-per-pixel */
	"48 48 90 1 ",
	"  c None",
	". c #414141",
	"X c gray26",
	"o c #434343",
	"O c #444342",
	"+ c #444343",
	"@ c #454442",
	"# c #464442",
	"$ c #464542",
	"% c #534D43",
	"& c #6D5D45",
	"* c #705F45",
	"= c #7B6545",
	"- c #8F7146",
	"; c #947446",
	": c #997847",
	"> c #FF9800",
	", c #F89A0C",
	"< c #FF9E0E",
	"1 c #E3A032",
	"2 c #E2A034",
	"3 c #E3A135",
	"4 c #E4A135",
	"5 c #FFAB30",
	"6 c #A98248",
	"7 c #B68A49",
	"8 c #C09049",
	"9 c #C49249",
	"0 c #C6944A",
	"q c #D39B4A",
	"w c #E1A54C",
	"e c #EFAD4C",
	"r c #FFB344",
	"t c #FFB64B",
	"y c #FBB44C",
	"u c #FFB64C",
	"i c #FFB74C",
	"p c #FEB64D",
	"a c #FFB64D",
	"s c #FEB74D",
	"d c #FFB74D",
	"f c #FEB74E",
	"g c #FFB74E",
	"h c #FFB84D",
	"j c #FFB84E",
	"k c #E8B35E",
	"l c #E9B45D",
	"z c #DFB365",
	"x c #E5B360",
	"c c #E5B361",
	"v c #E4B462",
	"b c #77A4B3",
	"n c #3F9ADD",
	"m c #3E9BDE",
	"M c #2796EE",
	"N c #2A97EC",
	"B c #2A97ED",
	"V c #2897EF",
	"C c #2195F2",
	"Z c #2195F3",
	"A c #2196F3",
	"S c #2296F2",
	"D c #2397F2",
	"F c #2096F4",
	"G c #3AA2F5",
	"H c #3FA4F4",
	"J c #5B9EC7",
	"K c #409BDB",
	"L c #429BDA",
	"P c #439BDA",
	"I c #459BD9",
	"U c #64A2C1",
	"Y c #62A1C4",
	"T c #42A6F5",
	"R c #48A8F5",
	"E c #56AFF6",
	"W c #5EB3F7",
	"Q c #6AB9F7",
	"! c #6DBAF7",
	"~ c #6DB9F8",
	"^ c #6EBAF8",
	"/ c #76BEF7",
	"( c #78C0F7",
	") c #B1BCB0",
	"_ c #B0BCB2",
	"` c #84C5F9",
	"' c #85C5F9",
	"] c #8EC9F9",
	"[ c #8FCAF9",
	"{ c #90CAF9",
	/* pixels */
	"                                                ",
	"                                                ",
	"                                                ",
	"                      XXXXX                     ",
	"                     XXXXXX                     ",
	"                    XXXXXXXXX                   ",
	"                   XXXXXXXXXXX                  ",
	"                   XXXXXX&7q@XX                 ",
	"                  OXXX%:wgth6XX                 ",
	"                  @@=9ygggggg&@                 ",
	"                  @8thhgghghh9@                 ",
	"                  X0ggtggtgtg0X                 ",
	"                  X0hggghthtg0X                 ",
	"                  ;0tgthggggg0-                 ",
	"                  gehghtgthgteg                 ",
	"                  ggtgggghtgggg                 ",
	"     t             ghggggtgthg             g    ",
	"     gg             tgthghggg             gg    ",
	"     hg              ggggtht              th    ",
	"     gh              <5rtr5<              gg    ",
	"     gg              >>>>>>>              gg    ",
	"     ggt            ^1>>>>>2^            ght    ",
	"     ggg           ({)>>>>>_{/           ggg    ",
	"     htg         FAR{{)3,4_{[TAA         gtg    ",
	"     gth        CAAAW[{{{{[[EAAA         gtg    ",
	"     gggg       AAAAAT!`[`QGAAAAD       gghg    ",
	"      thg      MAAAAAAAAAAAAAAAAAN      gtg     ",
	"      gggg     AAAAAAAAAAAAAAAAAAD     gghg     ",
	"      gggg    VAAAAAAAAAAAAAAAAAAAN    gggg     ",
	"       ghtg  KAAAAAAAAAAAAAAAAAAAAAP  ghth      ",
	"       gggg UAAAAAAAAAAAAAAAAAAAAAAAb gtgg      ",
	"       htgggvnAAAAAAAAAAAAAAAAAAAAAKlgghtg      ",
	"        gghggxnAAAAAAAAAAAAAAAAAAAPlhgggg       ",
	"        tgtgthvnYAAAAAAAAAAAAAAAJKkgtgthg       ",
	"        hggggggz AAAAAAAAAAAAAAA xgghgtgg       ",
	"         gthtgh  AAAAAAAAAAAAAAA  httggg        ",
	"         hgghg   AAAAAAAAAAAAAAA   ggghg        ",
	"           gh    AAAAAAAAAAAAAAA    tg          ",
	"                 AAAAAAAAAAAAAAA                ",
	"                 AAAAAAAAAAAAAAA                ",
	"                 AAAAAAAAAAAAAAA                ",
	"                 AAAAAAAAAAAAAAA                ",
	"                 AAAAAAAAAAAAAAA                ",
	"                 AAAAAAAAAAAAAAA                ",
	"                 AAAAAAAAAAAAAAA                ",
	"                                                ",
	"                                                ",
	"                                                "
};
